In [1]:
import pandas as pd 
import numpy as np 
import pylab as pl 
# import numpy as np
import matplotlib.pyplot as plt

from numpy import *  # 导入 numpy 的所有全局函数
from matplotlib.pyplot import *  # 导入 pyplot 的所有全局函数
import geopandas as gp 
import sys 
sys.path.insert(0, '/home/zli333/hpchome/network_conditioning/codes/')
import network_functions as netf

import os
import struct

import sys, subprocess

In [2]:
net = pd.read_parquet('../hlm_data/structure/sangamon.gzip')

In [4]:
net.columns
# np: num of the parents
# us1/us2: upstream lids, eliminating the ghost links(without area information)


# use this streamorder to divide the watershed into smaller parts
# not using the gauges to divide, since we are just using the one outlet gauge
# start with the most downstream outlet link, we have a initial Cr
# track upstream for partition
# each time the order changes, consider adding an extra Cr value to this upstream area(upstream links)

Index(['DSLINKNO', 'USLINKNO1', 'USLINKNO2', 'DSNODEID', 'strmOrder', 'Length',
       'Magnitude', 'DSContArea', 'strmDrop', 'Slope', 'StraightL',
       'USContArea', 'WSNO', 'DOUTEND', 'DOUTSTART', 'DOUTMID', 'np', 'us1',
       'us2', 'us3', 'us4', 'us5', 'us6', 'us7', 'us8', 'us9', 'us10'],
      dtype='object')

In [5]:
net.head()

,DSLINKNO,USLINKNO1,USLINKNO2,DSNODEID,strmOrder,Length,Magnitude,DSContArea,strmDrop,Slope,...,us1,us2,us3,us4,us5,us6,us7,us8,us9,us10
LINKNO,,,,,,,,,,,,,,,,,,,,,
308545,308769,308321,18465,-1,9,634.4,58518,1.361449e+10,0.00,0.000000,...,308321,18465,-1,-1,-1,-1,-1,-1,-1,-1
308321,308545,308097,286594,-1,9,72.6,58517,1.361419e+10,0.00,0.000000,...,308097,286594,-1,-1,-1,-1,-1,-1,-1,-1
18465,308545,-1,-1,-1,1,611.9,1,2.081486e+05,3.57,0.005832,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
308097,308321,307873,124417,-1,9,471.8,58424,1.359396e+10,0.00,0.000000,...,307873,124417,-1,-1,-1,-1,-1,-1,-1,-1
286594,308321,283234,229698,-1,4,441.7,93,2.021831e+07,0.00,0.000000,...,283234,229698,-1,-1,-1,-1,-1,-1,-1,-1

In [17]:
net.loc[net['strmOrder']>=9]

,DSLINKNO,USLINKNO1,USLINKNO2,DSNODEID,strmOrder,Length,Magnitude,DSContArea,strmDrop,Slope,...,us1,us2,us3,us4,us5,us6,us7,us8,us9,us10
LINKNO,,,,,,,,,,,,,,,,,,,,,
308545,308769,308321,18465,-1,9,634.4,58518,1.361449e+10,0.00,0.000000,...,308321,18465,-1,-1,-1,-1,-1,-1,-1,-1
308321,308545,308097,286594,-1,9,72.6,58517,1.361419e+10,0.00,0.000000,...,308097,286594,-1,-1,-1,-1,-1,-1,-1,-1
308097,308321,307873,124417,-1,9,471.8,58424,1.359396e+10,0.00,0.000000,...,307873,124417,-1,-1,-1,-1,-1,-1,-1,-1
307873,308097,307649,44001,-1,9,142.2,58423,1.359368e+10,0.00,0.000000,...,307649,44001,-1,-1,-1,-1,-1,-1,-1,-1
307649,307873,284128,104925,-1,9,369.8,58422,1.359360e+10,0.00,0.000000,...,284128,104925,-1,-1,-1,-1,-1,-1,-1,-1
284128,307649,314367,4577,-1,9,264.2,58421,1.359259e+10,0.00,0.000000,...,314367,4577,-1,-1,-1,-1,-1,-1,-1,-1
314367,284128,314143,113663,-1,9,2659.0,58420,1.359238e+10,0.00,0.000000,...,314143,113663,-1,-1,-1,-1,-1,-1,-1,-1
314143,314367,313919,41535,-1,9,419.2,58419,1.359179e+10,0.00,0.000000,...,313919,41535,-1,-1,-1,-1,-1,-1,-1,-1
313919,314143,313695,258815,-1,9,506.5,58418,1.359172e+10,0.00,0.000000,...,313695,258815,-1,-1,-1,-1,-1,-1,-1,-1
313695,313919,316158,13087,-1,9,474.1,58414,1.359037e+10,0.00,0.000000,...,316158,13087,-1,-1,-1,-1,-1,-1,-1,-1
316158,313695,315934,272927,-1,9,1663.5,58413,1.359018e+10,0.00,0.000000,...,315934,272927,-1,-1,-1,-1,-1,-1,-1,-1
315934,316158,303836,298910,-1,9,338.2,58394,1.358603e+10,0.00,0.000000,...,303836,298910,-1,-1,-1,-1,-1,-1,-1,-1
303836,315934,303612,70428,-1,9,2847.5,58082,1.351455e+10,0.00,0.000000,...,303612,70428,-1,-1,-1,-1,-1,-1,-1,-1
303612,303836,300923,283228,-1,9,594.4,58081,1.351395e+10,0.00,0.000000,...,300923,283228,-1,-1,-1,-1,-1,-1,-1,-1
300923,303612,300699,261276,-1,9,3330.7,57994,1.349212e+10,0.00,0.000000,...,300699,261276,-1,-1,-1,-1,-1,-1,-1,-1
300699,300923,300475,298463,-1,9,804.8,57971,1.348554e+10,0.00,0.000000,...,300475,298463,-1,-1,-1,-1,-1,-1,-1,-1
300475,300699,300251,14428,-1,9,396.5,57372,1.334979e+10,0.00,0.000000,...,300251,14428,-1,-1,-1,-1,-1,-1,-1,-1
300251,300475,300027,266652,-1,9,237.7,57371,1.334958e+10,0.00,0.000000,...,300027,266652,-1,-1,-1,-1,-1,-1,-1,-1
300027,300251,299803,151963,-1,9,171.6,57304,1.333497e+10,0.00,0.000000,...,299803,151963,-1,-1,-1,-1,-1,-1,-1,-1
299803,300027,299579,82523,-1,9,53.8,57302,1.333469e+10,0.00,0.000000,...,299579,82523,-1,-1,-1,-1,-1,-1,-1,-1
299579,299803,290617,289499,-1,9,634.5,57301,1.333461e+10,0.00,0.000000,...,290617,289499,-1,-1,-1,-1,-1,-1,-1,-1
290617,299579,300248,185334,-1,9,1921.5,57112,1.329154e+10,0.00,0.000000,...,300248,185334,-1,-1,-1,-1,-1,-1,-1,-1
300248,290617,300024,57880,-1,9,937.4,57110,1.329030e+10,0.00,0.000000,...,300024,57880,-1,-1,-1,-1,-1,-1,-1,-1
300024,300248,287479,282999,-1,9,647.0,57109,1.329016e+10,0.00,0.000000,...,287479,282999,-1,-1,-1,-1,-1,-1,-1,-1
287479,300024,287255,185783,-1,9,486.3,55557,1.294317e+10,0.00,0.000000,...,287255,185783,-1,-1,-1,-1,-1,-1,-1,-1
287255,287479,287031,108951,-1,9,157.3,55554,1.294216e+10,0.00,0.000000,...,287031,108951,-1,-1,-1,-1,-1,-1,-1,-1
287031,287255,286807,174583,-1,9,1113.2,55553,1.294196e+10,0.00,0.000000,...,286807,174583,-1,-1,-1,-1,-1,-1,-1,-1
286807,287031,299800,4344,-1,9,55.3,55546,1.294009e+10,0.00,0.000000,...,299800,4344,-1,-1,-1,-1,-1,-1,-1,-1
299800,286807,299576,14648,-1,9,1046.3,55545,1.293994e+10,0.00,0.000000,...,299576,14648,-1,-1,-1,-1,-1,-1,-1,-1
299576,299800,299352,66392,-1,9,1760.7,55544,1.293981e+10,0.00,0.000000,...,299352,66392,-1,-1,-1,-1,-1,-1,-1,-1
299352,299576,299128,10168,-1,9,587.1,55543,1.293950e+10,0.00,0.000000,...,299128,10168,-1,-1,-1,-1,-1,-1,-1,-1
299128,299352,298904,128887,-1,9,727.2,55542,1.293937e+10,0.00,0.000000,...,298904,128887,-1,-1,-1,-1,-1,-1,-1,-1
298904,299128,298680,251641,-1,9,98.4,55541,1.293907e+10,0.00,0.000000,...,298680,251641,-1,-1,-1,-1,-1,-1,-1,-1
298680,298904,298456,48920,-1,9,481.5,55513,1.293314e+10,0.56,0.001170,...,298456,48920,-1,-1,-1,-1,-1,-1,-1,-1
298456,298680,298232,18904,-1,9,583.5,55512,1.293302e+10,0.48,0.000817,...,298232,18904,-1,-1,-1,-1,-1,-1,-1,-1
298232,298456,298008,5688,-1,9,1203.7,55511,1.293283e+10,0.00,0.000000,...,298008,5688,-1,-1,-1,-1,-1,-1,-1,-1
298008,298232,297784,231480,-1,9,673.4,55510,1.293256e+10,0.00,0.000000,...,297784,231480,-1,-1,-1,-1,-1,-1,-1,-1
297784,298008,297560,266873,-1,9,168.1,55507,1.293212e+10,0.00,0.000000,...,297560,266873,-1,-1,-1,-1,-1,-1,-1,-1
297560,297784,297336,245816,-1,9,434.6,55443,1.291787e+10,0.10,0.000231,...,297336,245816,-1,-1,-1,-1,-1,-1,-1,-1
297336,297560,297112,162488,-1,9,254.9,55440,1.291704e+10,0.68,0.002687,...,297112,162488,-1,-1,-1,-1,-1,-1,-1,-1
297112,297336,290393,7481,-1,9,536.0,55438,1.291663e+10,0.00,0.000000,...,290393,7481,-1,-1,-1,-1,-1,-1,-1,-1
290393,297112,290169,22041,-1,9,689.9,55437,1.291649e+10,0.00,0.000000,...,290169,22041,-1,-1,-1,-1,-1,-1,-1,-1
290169,290393,289945,157561,-1,9,369.8,55436,1.291636e+10,0.00,0.000000,...,289945,157561,-1,-1,-1,-1,-1,-1,-1,-1
289945,290169,289721,3673,-1,9,230.5,55434,1.291602e+10,0.00,0.000000,...,289721,3673,-1,-1,-1,-1,-1,-1,-1,-1
289721,289945,289497,215353,-1,9,221.9,55433,1.291563e+10,0.00,0.000000,...,289497,215353,-1,-1,-1,-1,-1,-1,-1,-1
289497,289721,289273,199449,-1,9,140.1,55429,1.291435e+10,0.00,0.000000,...,289273,199449,-1,-1,-1,-1,-1,-1,-1,-1
289273,289497,311450,289049,-1,9,1103.1,55426,1.291371e+10,0.00,0.000000,...,311450,289049,-1,-1,-1,-1,-1,-1,-1,-1